#!/bin/bash

# VARIABLES
# Driver max size
MAX_SIZE="1074747474"
# Backup path
BACKUP_PATH="/tmp/testing/"

# Check the current backup folder size
# (du = gets the folder size); (grep = only take numbers from the previous result); (tail = take the last result from the list generated by 'grep' command, wich corresponds to the total)
CURRENT_SIZE="`du -cs $BACKUP_PATH | grep -o '[0-9]*' | tail -n 1`"
if [ "$CURRENT_SIZE" -gt "$MAX_SIZE" ]; then
  echo "···> The current size ($CURRENT_SIZE) is bigger than max size ($MAX_SIZE)."
  # TODO delete oldes file
else
  echo "Current backup folder size is $CURRENT_SIZE, nothing changed"
fi

# REFERENCES:
# Check folder size: https://stackoverflow.com/questions/16661982/check-folder-size-in-bash#16662027
# Grep numbers from a result: https://askubuntu.com/questions/184204/how-do-i-fetch-only-numbers-in-grep#184216 and https://stackoverflow.com/questions/8402919/how-to-make-grep-select-only-numeric-values
# Get last result from grep: https://stackoverflow.com/questions/24014194/how-to-grep-the-last-occurrence-of-a-line-pattern#24014737
